[theme]
primaryColor="#cc4100"
backgroundColor="#00000070"
secondaryBackgroundColor="#0017469c"
textColor="#a7a7a7"

[server]
enableCORS=false
enableXsrfProtection=false

[browser]
gatherUsageStats=false
