[theme]
primaryColor="#636EFA"
backgroundColor="#FAFAFA"
secondaryBackgroundColor="#F0F2F6"
textColor="#1E1E1E"

[server]
enableCORS=false
enableXsrfProtection=false

[browser]
gatherUsageStats=false
