[theme]
primaryColor="#cc4100"
backgroundColor="#00000063"
secondaryBackgroundColor="#00174660"
textColor="#a7a7a727"

[server]
enableCORS=false
enableXsrfProtection=false

[browser]
gatherUsageStats=false
